---
title: "Welcome to STAT0002"
subtitle: "Introduction to Probability and Statistics"
author: "Paul Northrop"
date: "Live session: 12:00 Tuesday 29 September 2020"
output: ioslides_presentation
lang: "en-gb"
---

<!--
Comments in here.
-->

## What is STAT0002?

An accessible and application-oriented introduction to basic ideas in Probability and Statistics.

STAT0002 is **not** a maths module.  It is important that you can formalise arguments clearly using maths, but statistics is about more than maths.

**I did not take A-level Statistics (or equivalent). Will this matter?**

No.  Knowledge of A-level Statistics is not assumed.

**I did take A-level Statistics. Do I know all of this already?**

No, probably not.  Deeper understanding and the ability to apply principles to unseen problems is required at university.

## Teaching and learning

* [Moodle](https://www.ucl.ac.uk/moodle) (UCL's VLE) provides structure and guidance
* Lecture notes
* Watch short videos before live sessions
* Q&A, discussion, unseen material
* Weekly exercises and tutorials
* Online quizzes
* Discussion forum and office hours

## Assessment

* Participation (10%)
    - peer-to-peer feedback
* Meet your Professor In-course Assessment (15%)
    - Work in groups
    - Read a research paper
    - Interview the Professor
    - Write a brief summary of the paper
* Written examination in the summer (75%)
 
## Questions?

* Live Q&A session at 12:00 on Tuesday 29th September 
* Please post your questions about STAT0002 to the relevant Moodle forum

### At the live session

* I will answer as many questions as possible at the session
* Others will be answered in the forum
* You may also ask questions live at the session
* I will also pose some quiz questions for you to answer live
